const seed = JSON.parse(localStorage.getItem('anorachartsData')||'null');
if(!seed){location.href='index.html'}
let data=JSON.parse(localStorage.getItem('anorachartsData'));
const app=document.getElementById('adminApp'),title=document.getElementById('viewTitle');
const save=()=>localStorage.setItem('anorachartsData',JSON.stringify(data));
const uid=p=>p+Date.now().toString(36);
const byId=(l,id)=>l.find(x=>x.id===id);
const artistName=id=>byId(data.artists,id)?.name||'Unknown';
const albumName=id=>byId(data.albums,id)?.title||'Single';
function setView(v){document.querySelectorAll('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));title.textContent=v==='chart'?'Hot 100':v[0].toUpperCase()+v.slice(1);render(v)}
document.getElementById('adminNav').onclick=e=>{if(e.target.dataset.view)setView(e.target.dataset.view)};
function render(v){({dashboard,artists,albums,songs,chart,awards,stories}[v]||dashboard)()}
function dashboard(){const week=data.chartWeeks.filter(w=>w.status==='published').sort((a,b)=>b.date.localeCompare(a.date))[0];app.innerHTML=`<div class="stats"><div class="stat"><strong>${data.songs.length}</strong><span>Songs</span></div><div class="stat"><strong>${data.artists.length}</strong><span>Artists</span></div><div class="stat"><strong>${data.albums.length}</strong><span>Albums</span></div><div class="stat"><strong>${data.chartWeeks.length}</strong><span>Chart Weeks</span></div></div><div class="panel"><div class="panel-head"><strong>Latest Published Chart</strong></div><div class="panel-body"><h2>${week?new Date(week.date+'T12:00').toLocaleDateString('en-US',{dateStyle:'long'}):'No chart published'}</h2><p class="notice">Changes you make here are saved to localStorage and immediately appear on the public site in this demo.</p></div></div>`}
function artists(){app.innerHTML=`<div class="panel"><div class="panel-head"><strong>Add Artist</strong></div><div class="panel-body"><form id="artistForm" class="form-grid"><div><label>Artist name</label><input name="name" required></div><div><label>Genre</label><input name="genre"></div><div class="full"><label>Artist image URL</label><input name="image" required placeholder="https://..."><img id="artistPreview" class="preview" style="display:none"></div><div class="full"><button class="primary">Add Artist</button></div></form></div></div>${artistTable()}`;wirePreview('artistForm','image','artistPreview');document.getElementById('artistForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.artists.push({id:uid('a'),name:f.get('name'),genre:f.get('genre'),image:f.get('image')});save();artists()}}
function artistTable(){return `<div class="panel"><div class="panel-head"><strong>Artists</strong></div><div class="panel-body"><table class="table"><thead><tr><th>Image</th><th>Name</th><th>Genre</th><th></th></tr></thead><tbody>${data.artists.map(a=>`<tr><td><img class="thumb" src="${a.image}"></td><td>${a.name}</td><td>${a.genre||''}</td><td><button class="danger" onclick="deleteArtist('${a.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
window.deleteArtist=id=>{if(confirm('Delete this artist? Related content may be affected.')){data.artists=data.artists.filter(x=>x.id!==id);save();artists()}}
function albums(){app.innerHTML=`<div class="panel"><div class="panel-head"><strong>Add Album</strong></div><div class="panel-body"><form id="albumForm" class="form-grid"><div><label>Album title</label><input name="title" required></div><div><label>Artist</label><select name="artistId">${data.artists.map(a=>`<option value="${a.id}">${a.name}</option>`)}</select></div><div><label>Year</label><input name="year" type="number" value="2026"></div><div><label>Cover image URL</label><input name="cover" required placeholder="https://..."></div><div class="full"><img id="albumPreview" class="preview" style="display:none"></div><div class="full"><button class="primary">Add Album</button></div></form></div></div><div class="panel"><div class="panel-head"><strong>Albums</strong></div><div class="panel-body"><table class="table"><thead><tr><th>Cover</th><th>Album</th><th>Artist</th><th>Year</th><th></th></tr></thead><tbody>${data.albums.map(al=>`<tr><td><img class="thumb" src="${al.cover}"></td><td>${al.title}</td><td>${artistName(al.artistId)}</td><td>${al.year||''}</td><td><button class="danger" onclick="deleteAlbum('${al.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`;wirePreview('albumForm','cover','albumPreview');document.getElementById('albumForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.albums.push({id:uid('al'),title:f.get('title'),artistId:f.get('artistId'),year:+f.get('year'),cover:f.get('cover')});save();albums()}}
window.deleteAlbum=id=>{if(confirm('Delete this album?')){data.albums=data.albums.filter(x=>x.id!==id);save();albums()}}
function songs(){app.innerHTML=`<div class="panel"><div class="panel-head"><strong>Add Song</strong></div><div class="panel-body"><form id="songForm" class="form-grid"><div><label>Song title</label><input name="title" required></div><div><label>Artist</label><select name="artistId">${data.artists.map(a=>`<option value="${a.id}">${a.name}</option>`)}</select></div><div><label>Album</label><select name="albumId"><option value="">No album</option>${data.albums.map(al=>`<option value="${al.id}">${al.title}</option>`)}</select></div><div><label>Optional song artwork URL</label><input name="artwork" placeholder="Uses album cover if empty"></div><div class="full"><button class="primary">Add Song</button></div></form></div></div><div class="panel"><div class="panel-head"><strong>Songs</strong></div><div class="panel-body"><table class="table"><thead><tr><th>Song</th><th>Artist</th><th>Album</th><th></th></tr></thead><tbody>${data.songs.map(s=>`<tr><td>${s.title}</td><td>${artistName(s.artistId)}</td><td>${albumName(s.albumId)}</td><td><button class="danger" onclick="deleteSong('${s.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`;document.getElementById('songForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.songs.push({id:uid('s'),title:f.get('title'),artistId:f.get('artistId'),albumId:f.get('albumId'),artwork:f.get('artwork')});save();songs()}}
window.deleteSong=id=>{if(confirm('Delete this song? Historical entries may reference it.')){data.songs=data.songs.filter(x=>x.id!==id);data.chartWeeks.forEach(w=>w.entries=w.entries.filter(e=>e.songId!==id));save();songs()}}
function chart(){const w=data.chartWeeks.sort((a,b)=>b.date.localeCompare(a.date))[0];app.innerHTML=`<div class="panel"><div class="panel-head"><strong>Current Chart Week</strong><button class="primary" id="newWeekBtn">Create New Week</button></div><div class="panel-body">${w?`<div class="form-grid"><div><label>Chart date</label><input id="chartDate" type="date" value="${w.date}"></div><div><label>Status</label><select id="chartStatus"><option ${w.status==='published'?'selected':''}>published</option><option ${w.status==='draft'?'selected':''}>draft</option></select></div></div><div style="margin-top:20px">${w.entries.sort((a,b)=>a.rank-b.rank).map(e=>{const s=byId(data.songs,e.songId);return `<div class="chart-admin-row"><div class="rankbox">${e.rank}</div><div><strong>${s?.title||'Missing song'}</strong><div class="notice">${s?artistName(s.artistId):''}</div></div><input type="number" value="${e.points}" onchange="updatePoints('${w.id}','${e.songId}',this.value)"><button class="danger" onclick="removeEntry('${w.id}','${e.songId}')">Remove</button></div>`}).join('')}</div><div style="margin-top:18px" class="form-grid"><div><label>Add song</label><select id="addSongSelect">${data.songs.filter(s=>!w.entries.some(e=>e.songId===s.id)).map(s=>`<option value="${s.id}">${s.title} — ${artistName(s.artistId)}</option>`)}</select></div><div style="align-self:end"><button class="primary" id="addSongBtn">Add to Chart</button></div></div>`:'No chart week yet.'}</div></div>`;
if(w){document.getElementById('chartDate').onchange=e=>{w.date=e.target.value;save()};document.getElementById('chartStatus').onchange=e=>{w.status=e.target.value;save()};document.getElementById('addSongBtn').onclick=()=>{const id=document.getElementById('addSongSelect').value;if(!id)return;const prev=data.chartWeeks.filter(x=>x.id!==w.id&&x.status==='published').sort((a,b)=>b.date.localeCompare(a.date))[0];const pe=prev?.entries.find(x=>x.songId===id);w.entries.push({songId:id,rank:w.entries.length+1,previousRank:pe?.rank??null,points:0,peak:pe?.peak??w.entries.length+1,weeks:(pe?.weeks||0)+1});save();chart()}}
document.getElementById('newWeekBtn').onclick=()=>{const date=prompt('Chart date (YYYY-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;data.chartWeeks.push({id:uid('w'),date,status:'draft',entries:[]});save();chart()}}
window.updatePoints=(wid,sid,val)=>{const w=byId(data.chartWeeks,wid),e=w.entries.find(x=>x.songId===sid);e.points=+val;save()};window.removeEntry=(wid,sid)=>{const w=byId(data.chartWeeks,wid);w.entries=w.entries.filter(x=>x.songId!==sid);w.entries.forEach((e,i)=>e.rank=i+1);save();chart()}
function awards(){app.innerHTML=`<div class="panel"><div class="panel-head"><strong>Awards</strong></div><div class="panel-body"><form id="awardForm" class="form-grid"><div><label>Category</label><input name="category" required></div><div><label>Winner type</label><select name="winnerType" id="winnerType"><option value="artist">Artist</option><option value="song">Song</option><option value="album">Album</option></select></div><div class="full"><label>Winner</label><select name="winnerId" id="winnerId"></select></div><div class="full"><button class="primary">Add Award</button></div></form></div></div><div class="panel"><div class="panel-body"><table class="table"><tbody>${data.awards.map((a,i)=>`<tr><td>${a.category}</td><td>${winnerLabel(a)}</td><td><button class="danger" onclick="deleteAward(${i})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`;const type=document.getElementById('winnerType'),sel=document.getElementById('winnerId');function fill(){const arr=type.value==='artist'?data.artists:type.value==='song'?data.songs:data.albums;sel.innerHTML=arr.map(x=>`<option value="${x.id}">${x.name||x.title}</option>`).join('')}type.onchange=fill;fill();document.getElementById('awardForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.awards.push({category:f.get('category'),winnerType:f.get('winnerType'),winnerId:f.get('winnerId')});save();awards()}}
function winnerLabel(a){const arr=a.winnerType==='artist'?data.artists:a.winnerType==='song'?data.songs:data.albums;const x=byId(arr,a.winnerId);return x?.name||x?.title||'Unknown'}window.deleteAward=i=>{data.awards.splice(i,1);save();awards()}
function stories(){app.innerHTML=`<div class="panel"><div class="panel-head"><strong>Add Chart Story</strong></div><div class="panel-body"><form id="storyForm" class="form-grid"><div class="full"><label>Headline</label><input name="headline" required></div><div class="full"><label>Description</label><textarea name="text" required></textarea></div><div class="full"><button class="primary">Add Story</button></div></form></div></div><div class="panel"><div class="panel-body">${data.stories.map((s,i)=>`<div style="padding:14px 0;border-bottom:1px solid #1d1d1d"><strong>${s.headline}</strong><p class="notice">${s.text}</p><button class="danger" onclick="deleteStory(${i})">Delete</button></div>`).join('')}</div></div>`;document.getElementById('storyForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.stories.push({headline:f.get('headline'),text:f.get('text')});save();stories()}}window.deleteStory=i=>{data.stories.splice(i,1);save();stories()}
function wirePreview(formId,inputName,imgId){const f=document.getElementById(formId),inp=f.elements[inputName],img=document.getElementById(imgId);inp.addEventListener('input',()=>{img.src=inp.value;img.style.display=inp.value?'block':'none'})}
document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset the demo data?')){localStorage.removeItem('anorachartsData');alert('Reload index.html once to restore the sample data.');location.href='index.html'}};
setView('dashboard');
