const DATA_KEY='anorachartsData';
const DATA_VERSION=2;
const $=s=>document.querySelector(s);
const app=$('#adminApp');
const title=$('#viewTitle');
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function load(){try{return JSON.parse(localStorage.getItem(DATA_KEY))||{}}catch(e){return {}}}
let data=load();
const save=()=>{data.version=DATA_VERSION;localStorage.setItem(DATA_KEY,JSON.stringify(data));};
const byId=(list,id)=>list.find(x=>x.id===id);
const artistName=id=>byId(data.artists,id)?.name||'Unknown';
const albumName=id=>byId(data.albums,id)?.title||'—';
const latestWeek=()=>[...(data.chartWeeks||[])].sort((a,b)=>b.date.localeCompare(a.date))[0];
const publicImage=(s)=>s.artwork||byId(data.albums,s.albumId)?.cover||'';
function ensureData(){if(!data.version){alert('Open index.html once first so the initial Top 100 demo data can be created.');location.href='index.html'}}
ensureData();

const views={dashboard,artists,albums,songs,chart,awards,stories};
function setView(v){document.querySelectorAll('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));title.textContent={dashboard:'Dashboard',artists:'Artists',albums:'Albums',songs:'Songs',chart:'Hot 100',awards:'Awards',stories:'Stories'}[v];views[v]();}
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));

function dashboard(){const w=latestWeek();app.innerHTML=`<div class="stats"><div class="stat"><strong>${data.songs.length}</strong><span>Songs</span></div><div class="stat"><strong>${data.artists.length}</strong><span>Artists</span></div><div class="stat"><strong>${data.albums.length}</strong><span>Albums</span></div><div class="stat"><strong>${w?.entries.length||0}</strong><span>Chart entries</span></div></div><div class="panel"><div class="panel-head"><strong>Control room</strong></div><div class="panel-body"><p class="notice">This admin panel controls the public site. Edit artists, album covers, songs and all 100 Hot 100 positions here. Changes are saved instantly in this browser.</p><div class="quick-actions"><button class="primary" onclick="setView('songs')">Add Song</button><button class="ghost" onclick="setView('artists')">Edit Artists</button><button class="ghost" onclick="setView('albums')">Edit Albums</button><button class="ghost" onclick="setView('chart')">Manage Hot 100</button></div></div></div>`}
window.setView=setView;

function imageFields(prefix,current=''){return `<div class="full media-field"><label>Image</label><div class="media-row"><img id="${prefix}Preview" class="preview" src="${esc(current)}" style="${current?'':'display:none'}"><div class="media-inputs"><input name="imageUrl" placeholder="Paste image URL" value="${esc(current)}"><label class="file-btn">Upload image<input name="imageFile" type="file" accept="image/png,image/jpeg,image/webp" hidden></label><small>Upload JPG, PNG or WEBP. The image is compressed for this local demo.</small></div></div></div>`}
async function imageFromForm(form,current=''){const url=form.elements.imageUrl?.value.trim();const file=form.elements.imageFile?.files?.[0];if(file)return await compressImage(file);return url||current||''}
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=520,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
function wireImage(form,prefix){const preview=document.getElementById(prefix+'Preview');const url=form.elements.imageUrl,file=form.elements.imageFile;url?.addEventListener('input',()=>{preview.src=url.value;preview.style.display=url.value?'block':'none'});file?.addEventListener('change',()=>{if(file.files[0]){const o=URL.createObjectURL(file.files[0]);preview.src=o;preview.style.display='block'}})}
function modal(html){let m=document.getElementById('modal');if(!m){m=document.createElement('div');m.id='modal';m.className='modal';document.body.appendChild(m)}m.innerHTML=`<div class="modal-card"><button class="modal-close" onclick="closeModal()">✕</button>${html}</div>`;m.classList.add('open')}
window.closeModal=()=>document.getElementById('modal')?.classList.remove('open');

function artists(){app.innerHTML=`<div class="toolbar"><div><strong>${data.artists.length} artists</strong><div class="notice">Edit names, photos, genres and bios. Changes update the public Artists page immediately.</div></div><button class="primary" onclick="openArtist()">+ Add Artist</button></div><div class="panel"><div class="panel-body table-wrap"><table class="table"><thead><tr><th>Photo</th><th>Artist</th><th>Genre</th><th>Country</th><th>Actions</th></tr></thead><tbody>${data.artists.map(a=>`<tr><td><img class="thumb" src="${esc(a.image)}"></td><td><strong>${esc(a.name)}</strong></td><td>${esc(a.genre||'')}</td><td>${esc(a.country||'')}</td><td><div class="row-actions"><button class="ghost" onclick="openArtist('${a.id}')">Edit</button><button class="danger" onclick="deleteArtist('${a.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
window.openArtist=id=>{const a=id?byId(data.artists,id):{name:'',genre:'',country:'',bio:'',image:''};modal(`<h2>${id?'Edit':'Add'} Artist</h2><form id="artistEdit" class="form-grid"><div><label>Artist name</label><input name="name" value="${esc(a.name)}" required></div><div><label>Genre</label><input name="genre" value="${esc(a.genre||'')}"></div><div><label>Country</label><input name="country" value="${esc(a.country||'')}"></div><div class="full"><label>Biography</label><textarea name="bio">${esc(a.bio||'')}</textarea></div>${imageFields('artist',a.image)}<div class="full form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save Artist</button></div></form>`);const f=document.getElementById('artistEdit');wireImage(f,'artist');f.onsubmit=async e=>{e.preventDefault();const image=await imageFromForm(f,a.image);const obj={id:id||uid('a'),name:f.name.value.trim(),genre:f.genre.value.trim(),country:f.country.value.trim(),bio:f.bio.value.trim(),image};if(id)Object.assign(a,obj);else data.artists.push(obj);save();closeModal();artists()}}
window.deleteArtist=id=>{const usedSongs=data.songs.filter(s=>s.artistId===id).length,usedAlbums=data.albums.filter(a=>a.artistId===id).length;if(!confirm(`Delete this artist? ${usedSongs} songs and ${usedAlbums} albums currently reference them.`))return;data.artists=data.artists.filter(a=>a.id!==id);save();artists()}

function albums(){app.innerHTML=`<div class="toolbar"><div><strong>${data.albums.length} albums</strong><div class="notice">Album covers automatically appear on songs that do not have separate artwork.</div></div><button class="primary" onclick="openAlbum()">+ Add Album</button></div><div class="panel"><div class="panel-body table-wrap"><table class="table"><thead><tr><th>Cover</th><th>Album</th><th>Artist</th><th>Year</th><th>Type</th><th>Actions</th></tr></thead><tbody>${data.albums.map(al=>`<tr><td><img class="thumb" src="${esc(al.cover)}"></td><td><strong>${esc(al.title)}</strong></td><td>${esc(artistName(al.artistId))}</td><td>${esc(al.year||'')}</td><td>${esc(al.type||'Album')}</td><td><div class="row-actions"><button class="ghost" onclick="openAlbum('${al.id}')">Edit</button><button class="danger" onclick="deleteAlbum('${al.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
window.openAlbum=id=>{const al=id?byId(data.albums,id):{title:'',artistId:data.artists[0]?.id||'',cover:'',year:2026,genre:'',type:'Album'};modal(`<h2>${id?'Edit':'Add'} Album</h2><form id="albumEdit" class="form-grid"><div><label>Album title</label><input name="title" value="${esc(al.title)}" required></div><div><label>Artist</label><select name="artistId">${data.artists.map(a=>`<option value="${a.id}" ${a.id===al.artistId?'selected':''}>${esc(a.name)}</option>`)}</select></div><div><label>Year</label><input name="year" type="number" value="${esc(al.year||2026)}"></div><div><label>Type</label><select name="type">${['Album','EP','Mixtape','Single Project'].map(t=>`<option ${t===al.type?'selected':''}>${t}</option>`)}</select></div><div class="full"><label>Genre</label><input name="genre" value="${esc(al.genre||'')}"></div>${imageFields('album',al.cover)}<div class="full form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save Album</button></div></form>`);const f=document.getElementById('albumEdit');wireImage(f,'album');f.onsubmit=async e=>{e.preventDefault();const cover=await imageFromForm(f,al.cover);const obj={id:id||uid('al'),title:f.title.value.trim(),artistId:f.artistId.value,year:+f.year.value||2026,type:f.type.value,genre:f.genre.value.trim(),cover};if(id)Object.assign(al,obj);else data.albums.push(obj);save();closeModal();albums()}}
window.deleteAlbum=id=>{const used=data.songs.filter(s=>s.albumId===id).length;if(!confirm(`Delete this album? ${used} songs currently reference it.`))return;data.albums=data.albums.filter(a=>a.id!==id);save();albums()}

function songs(){app.innerHTML=`<div class="toolbar"><div><strong>${data.songs.length} songs</strong><div class="notice">Add or edit songs here, then place them in any Hot 100 chart week.</div></div><button class="primary" onclick="openSong()">+ Add Song</button></div><div class="panel"><div class="panel-body"><input id="songSearch" class="search-admin" placeholder="Search songs or artists..."><div class="table-wrap"><table class="table"><thead><tr><th>Art</th><th>Song</th><th>Artist</th><th>Album</th><th>Actions</th></tr></thead><tbody id="songRows">${songRows('')}</tbody></table></div></div></div>`;document.getElementById('songSearch').oninput=e=>document.getElementById('songRows').innerHTML=songRows(e.target.value)}
function songRows(q){q=q.toLowerCase();return data.songs.filter(s=>!q||s.title.toLowerCase().includes(q)||artistName(s.artistId).toLowerCase().includes(q)).map(s=>`<tr><td><img class="thumb" src="${esc(publicImage(s))}"></td><td><strong>${esc(s.title)}</strong></td><td>${esc(artistName(s.artistId))}</td><td>${esc(albumName(s.albumId))}</td><td><div class="row-actions"><button class="ghost" onclick="openSong('${s.id}')">Edit</button><button class="danger" onclick="deleteSong('${s.id}')">Delete</button></div></td></tr>`).join('')}
window.openSong=id=>{const s=id?byId(data.songs,id):{title:'',artistId:data.artists[0]?.id||'',albumId:'',artwork:'',releaseDate:'',genre:''};modal(`<h2>${id?'Edit':'Add'} Song</h2><form id="songEdit" class="form-grid"><div><label>Song title</label><input name="title" value="${esc(s.title)}" required></div><div><label>Main artist</label><select name="artistId">${data.artists.map(a=>`<option value="${a.id}" ${a.id===s.artistId?'selected':''}>${esc(a.name)}</option>`)}</select></div><div><label>Album</label><select name="albumId"><option value="">No album / single</option>${data.albums.map(a=>`<option value="${a.id}" ${a.id===s.albumId?'selected':''}>${esc(a.title)} — ${esc(artistName(a.artistId))}</option>`)}</select></div><div><label>Release date</label><input name="releaseDate" type="date" value="${esc(s.releaseDate||'')}"></div><div class="full"><label>Genre</label><input name="genre" value="${esc(s.genre||'')}"></div>${imageFields('song',s.artwork)}<div class="full notice">Leave song artwork empty to automatically use its album cover.</div><div class="full form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save Song</button></div></form>`);const f=document.getElementById('songEdit');wireImage(f,'song');f.onsubmit=async e=>{e.preventDefault();const artwork=await imageFromForm(f,s.artwork);const obj={id:id||uid('s'),title:f.title.value.trim(),artistId:f.artistId.value,albumId:f.albumId.value,releaseDate:f.releaseDate.value,genre:f.genre.value.trim(),artwork};if(id)Object.assign(s,obj);else data.songs.push(obj);save();closeModal();songs()}}
window.deleteSong=id=>{const count=data.chartWeeks.reduce((n,w)=>n+w.entries.filter(e=>e.songId===id).length,0);if(!confirm(`Delete this song? It appears in ${count} chart entries.`))return;data.songs=data.songs.filter(s=>s.id!==id);data.chartWeeks.forEach(w=>{w.entries=w.entries.filter(e=>e.songId!==id);normalizeRanks(w)});save();songs()}

function chart(){const weeks=[...data.chartWeeks].sort((a,b)=>b.date.localeCompare(a.date));const w=byId(data.chartWeeks,sessionStorage.getItem('adminWeek'))||weeks[0];if(w)sessionStorage.setItem('adminWeek',w.id);app.innerHTML=`<div class="toolbar"><div><strong>Hot 100 Manager</strong><div class="notice">Manage up to 100 positions. Ranking order on this screen is exactly what users see.</div></div><button class="primary" onclick="createWeek()">+ New Chart Week</button></div>${w?`<div class="panel"><div class="panel-head chart-head"><div class="chart-select-wrap"><label>Chart week</label><select id="weekPicker">${weeks.map(x=>`<option value="${x.id}" ${x.id===w.id?'selected':''}>${x.date} · ${x.status} · ${x.entries.length} entries</option>`)}</select></div><div class="row-actions"><button class="ghost" onclick="duplicateWeek('${w.id}')">Duplicate previous</button><button class="${w.status==='published'?'ghost':'primary'}" onclick="togglePublish('${w.id}')">${w.status==='published'?'Unpublish':'Publish chart'}</button></div></div><div class="panel-body"><div class="form-grid"><div><label>Chart date</label><input id="chartDate" type="date" value="${esc(w.date)}"></div><div><label>Chart name</label><input id="chartName" value="${esc(w.name||'Anoracharts Hot 100')}"></div></div><div class="chart-progress"><strong>${w.entries.length}/100</strong><span>${w.entries.length===100?'Complete Hot 100':'Add '+(100-w.entries.length)+' more songs to fill the Hot 100'}</span><div><i style="width:${Math.min(100,w.entries.length)}%"></i></div></div><div class="chart-add"><select id="addSongSelect"><option value="">Select a song...</option>${data.songs.filter(s=>!w.entries.some(e=>e.songId===s.id)).map(s=>`<option value="${s.id}">${esc(s.title)} — ${esc(artistName(s.artistId))}</option>`)}</select><button class="primary" id="addSongBtn" ${w.entries.length>=100?'disabled':''}>Add to chart</button></div><div class="table-wrap"><table class="table chart-table"><thead><tr><th>Rank</th><th>Art</th><th>Song</th><th>Artist</th><th>Points</th><th>Prev</th><th>Peak</th><th>Move</th><th>Actions</th></tr></thead><tbody>${[...w.entries].sort((a,b)=>a.rank-b.rank).map(e=>chartRow(w,e)).join('')}</tbody></table></div></div></div>`:'<div class="panel"><div class="panel-body">No chart week yet.</div></div>'}`;
if(!w)return;document.getElementById('weekPicker').onchange=e=>{sessionStorage.setItem('adminWeek',e.target.value);chart()};document.getElementById('chartDate').onchange=e=>{w.date=e.target.value;save()};document.getElementById('chartName').onchange=e=>{w.name=e.target.value;save()};document.getElementById('addSongBtn').onclick=()=>{const sid=document.getElementById('addSongSelect').value;if(sid)addToChart(w.id,sid)};}
function chartRow(w,e){const s=byId(data.songs,e.songId);const diff=e.previousRank==null?'NEW':e.previousRank-e.rank>0?`+${e.previousRank-e.rank}`:e.previousRank-e.rank<0?`${e.previousRank-e.rank}`:'—';return `<tr><td><input class="rank-input" type="number" min="1" max="100" value="${e.rank}" onchange="setRank('${w.id}','${e.songId}',this.value)"></td><td><img class="thumb" src="${esc(s?publicImage(s):'')}"></td><td><strong>${esc(s?.title||'Missing song')}</strong></td><td>${esc(s?artistName(s.artistId):'')}</td><td><input class="points-input" type="number" min="0" value="${Number(e.points||0)}" onchange="updatePoints('${w.id}','${e.songId}',this.value)"></td><td>${e.previousRank??'NEW'}</td><td>#${e.peak||e.rank}</td><td>${diff}</td><td><div class="row-actions"><button class="mini" onclick="moveEntry('${w.id}','${e.songId}',-1)">↑</button><button class="mini" onclick="moveEntry('${w.id}','${e.songId}',1)">↓</button><button class="danger mini" onclick="removeEntry('${w.id}','${e.songId}')">Remove</button></div></td></tr>`}
function normalizeRanks(w){w.entries.sort((a,b)=>a.rank-b.rank);w.entries.forEach((e,i)=>{e.rank=i+1;e.peak=Math.min(e.peak||e.rank,e.rank)});}
window.addToChart=(wid,sid)=>{const w=byId(data.chartWeeks,wid);if(!w||w.entries.length>=100||w.entries.some(e=>e.songId===sid))return;const previous=data.chartWeeks.filter(x=>x.id!==wid&&x.status==='published'&&x.date<w.date).sort((a,b)=>b.date.localeCompare(a.date))[0];const pe=previous?.entries.find(e=>e.songId===sid);w.entries.push({songId:sid,rank:w.entries.length+1,previousRank:pe?.rank??null,points:0,peak:pe?.peak??w.entries.length+1,weeks:(pe?.weeks||0)+1});save();chart()}
window.setRank=(wid,sid,val)=>{const w=byId(data.chartWeeks,wid);let target=Math.max(1,Math.min(w.entries.length,Number(val)||1));const arr=[...w.entries].sort((a,b)=>a.rank-b.rank);const idx=arr.findIndex(e=>e.songId===sid);const [item]=arr.splice(idx,1);arr.splice(target-1,0,item);w.entries=arr;normalizeRanks(w);save();chart()}
window.moveEntry=(wid,sid,delta)=>{const w=byId(data.chartWeeks,wid);const arr=[...w.entries].sort((a,b)=>a.rank-b.rank);const idx=arr.findIndex(e=>e.songId===sid),next=idx+delta;if(next<0||next>=arr.length)return;[arr[idx],arr[next]]=[arr[next],arr[idx]];w.entries=arr;normalizeRanks(w);save();chart()}
window.updatePoints=(wid,sid,v)=>{const e=byId(data.chartWeeks,wid).entries.find(x=>x.songId===sid);e.points=Math.max(0,Number(v)||0);save()}
window.removeEntry=(wid,sid)=>{const w=byId(data.chartWeeks,wid);w.entries=w.entries.filter(e=>e.songId!==sid);normalizeRanks(w);save();chart()}
window.createWeek=()=>{const date=prompt('Chart date (YYYY-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;const w={id:uid('w'),date,status:'draft',name:'Anoracharts Hot 100',entries:[]};data.chartWeeks.push(w);save();sessionStorage.setItem('adminWeek',w.id);chart()}
window.duplicateWeek=id=>{const src=byId(data.chartWeeks,id);const date=prompt('New chart date (YYYY-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;const w={id:uid('w'),date,status:'draft',name:src.name||'Anoracharts Hot 100',entries:[...src.entries].sort((a,b)=>a.rank-b.rank).map(e=>({songId:e.songId,rank:e.rank,previousRank:e.rank,points:e.points,peak:e.peak,weeks:(e.weeks||0)+1}))};data.chartWeeks.push(w);save();sessionStorage.setItem('adminWeek',w.id);chart()}
window.togglePublish=id=>{const w=byId(data.chartWeeks,id);if(w.status!=='published'&&w.entries.length!==100&&!confirm(`This chart has ${w.entries.length}/100 entries. Publish anyway?`))return;w.status=w.status==='published'?'draft':'published';save();chart()}

function awards(){app.innerHTML=`<div class="toolbar"><div><strong>${data.awards.length} awards</strong></div><button class="primary" onclick="openAward()">+ Add Award</button></div><div class="panel"><div class="panel-body table-wrap"><table class="table"><thead><tr><th>Category</th><th>Winner</th><th>Type</th><th></th></tr></thead><tbody>${data.awards.map((a,i)=>`<tr><td><strong>${esc(a.category)}</strong></td><td>${esc(winnerLabel(a))}</td><td>${esc(a.winnerType)}</td><td><button class="danger" onclick="deleteAward(${i})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function winnerLabel(a){const list=a.winnerType==='artist'?data.artists:a.winnerType==='song'?data.songs:data.albums;const x=byId(list,a.winnerId);return x?.name||x?.title||'Unknown'}
window.openAward=()=>{modal(`<h2>Add Award</h2><form id="awardEdit" class="form-grid"><div class="full"><label>Category</label><input name="category" required></div><div><label>Winner type</label><select name="type" id="awardType"><option value="artist">Artist</option><option value="song">Song</option><option value="album">Album</option></select></div><div><label>Winner</label><select name="winner" id="awardWinner"></select></div><div class="full form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save Award</button></div></form>`);const f=document.getElementById('awardEdit'),type=f.type,winner=f.winner;const fill=()=>{const list=type.value==='artist'?data.artists:type.value==='song'?data.songs:data.albums;winner.innerHTML=list.map(x=>`<option value="${x.id}">${esc(x.name||x.title)}</option>`).join('')};type.onchange=fill;fill();f.onsubmit=e=>{e.preventDefault();data.awards.push({category:f.category.value.trim(),winnerType:type.value,winnerId:winner.value});save();closeModal();awards()}}
window.deleteAward=i=>{if(confirm('Delete this award?')){data.awards.splice(i,1);save();awards()}}
function stories(){app.innerHTML=`<div class="toolbar"><div><strong>${data.stories.length} chart stories</strong></div><button class="primary" onclick="openStory()">+ Add Story</button></div><div class="panel"><div class="panel-body">${data.stories.map((s,i)=>`<div class="story-admin"><div><strong>${esc(s.headline)}</strong><p>${esc(s.text)}</p></div><button class="danger" onclick="deleteStory(${i})">Delete</button></div>`).join('')}</div></div>`}
window.openStory=()=>{modal(`<h2>Add Chart Story</h2><form id="storyEdit" class="form-grid"><div class="full"><label>Headline</label><input name="headline" required></div><div class="full"><label>Description</label><textarea name="text" required></textarea></div><div class="full form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save Story</button></div></form>`);const f=document.getElementById('storyEdit');f.onsubmit=e=>{e.preventDefault();data.stories.unshift({headline:f.headline.value.trim(),text:f.text.value.trim()});save();closeModal();stories()}}
window.deleteStory=i=>{data.stories.splice(i,1);save();stories()}

document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset all local Anoracharts data? You will lose admin changes.')){localStorage.removeItem(DATA_KEY);location.href='index.html'}};
setView('dashboard');
